n = int(input('Quantos termos quer mostrar da sequência de fibonacci? '))
contador = 0
t1 = 0
t2 = 1
t3 = t1 + t2
print(f'{t1} -> {t2}', end='')
while contador != n - 2:
    contador += 1
    print(f' -> {t3}', end='')
    t1 = t2
    t2 = t3
    t3 = t1 + t2
